### ISSUE TITLE
Error 1221: Incorrect usage of DB GRANT and GLOBAL PRIVILEGES

### ISSUE THREAD

**Issue by jnordaas** [mhw/restic-backup-scripts#1]
When granting permissions to my database with the restic user, i get this error:

mysql> grant lock tables, select, show view, event, trigger, process on my_database* to 'restic'@'localhost';
ERROR 1221 (HY000): Incorrect usage of DB GRANT and GLOBAL PRIVILEGES

Why is this? am i doing something wrong on my side, or are the instructions misleading?

**Comment by mhw** [comment]
You're right. The `process` privilege is global and needs to be granted on `*.*`. I've updated the instructions with corrected commands.
